version: '2'
services:
  cassandra-node1:
    image: bitnami/cassandra:latest
    ports:
      - 9160:9160
      - 9042:9042
      - 7199:7199
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_USER=
      - CASSANDRA_PASSWORD=




#  messenger:
#    image: mrshish/messenger
#    ports:
#      - 3030:3030
#    depends_on:
#      - cassandra-node1
